# Generated by Django 3.2.9 on 2021-11-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hinchas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hincha_o_No', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='HinchasDeBoca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cant_Hinchas', models.IntegerField()),
                ('Equipo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='HinchasDeRiber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cant_Hinchas', models.IntegerField()),
                ('Equipo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='HinchasDeVelez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cant_Hinchas', models.IntegerField()),
                ('Equipo', models.CharField(max_length=15)),
            ],
        ),
    ]
