# Generated by Django 3.2.9 on 2021-11-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanBasquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=15)),
                ('es_o_no', models.BooleanField()),
                ('Equipo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FanFormula1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=15)),
                ('es_o_no', models.BooleanField()),
                ('Escuderia', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FanFutbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=15)),
                ('es_o_no', models.BooleanField()),
                ('equipo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FanVoley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=15)),
                ('es_o_no', models.BooleanField()),
                ('Equipo', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Hinchas',
        ),
        migrations.DeleteModel(
            name='HinchasDeBoca',
        ),
        migrations.DeleteModel(
            name='HinchasDeRiber',
        ),
        migrations.DeleteModel(
            name='HinchasDeVelez',
        ),
    ]
