# Generated by Django 3.2.9 on 2021-11-29 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_auto_20211125_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fanbasquet',
            old_name='Equipo',
            new_name='equipo',
        ),
        migrations.RenameField(
            model_name='fanbasquet',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='fanformula1',
            old_name='Escuderia',
            new_name='escuderia',
        ),
        migrations.RenameField(
            model_name='fanformula1',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='fanfutbol',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='fanvoley',
            old_name='Equipo',
            new_name='equipo',
        ),
        migrations.RenameField(
            model_name='fanvoley',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='fanfutbol',
            name='es_o_no',
        ),
    ]
