# Generated by Django 3.2.9 on 2021-11-29 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_auto_20211128_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fanbasquet',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='fanformula1',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='fanfutbol',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='fanvoley',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RemoveField(
            model_name='fanbasquet',
            name='es_o_no',
        ),
        migrations.RemoveField(
            model_name='fanformula1',
            name='es_o_no',
        ),
        migrations.RemoveField(
            model_name='fanvoley',
            name='es_o_no',
        ),
    ]
